spring:
  application:
    name: Catalog Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/salim-hbk/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
polar:
  greeting: Welcome to the catalog from a fresh config-2 server
