spring:
  application:
    name: Catalog Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/salim-hbk/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8888
polar:
  greeting: Welcome to the Config server book catalog!
